version: '3'
services:
  nav-nginx:
    image: nginx
    container_name: nav-nginx
    volumes:
      - .:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
    ports:
      - 8090:80
    restart: always
    depends_on:
      - nav-php-server
    environment:
      - TZ=Asia/Shanghai
  nav-php-server:
    image: php:7.4.33-fpm
    container_name: nav-php-server
    restart: always
    volumes:
      - .:/var/www/html
      - ./log:/var/log/php
    environment:
      - TZ=Asia/Shanghai